application: nyu-csci
version: 1
runtime: python
api_version: 1

handlers:

- url: /upload_hw
  script: grader.py

- url: /upload
  script: grader.py

- url: /(.*)
  script: grader.py
  login: required
  secure: always


builtins:
- remote_api: on
- datastore_admin: on
